#Conexion MySql
spring.datasource.url=jdbc:mysql://localhost:3306/zona_fit_db
spring.datasource.username=root
spring.datasource.pasword=admin
spring.datasource.driver-class-name=con.mysql.cj.jdb.Driver

#Evitar que se cree el esquema de la BD


# Usa jpa mediante hibernate para usar la API de persistencia(JPA)
spring.jpa.hibernate.ddl-auto=none 

# Show: No despligue detalle de las sentencias SQL(false) , desplegar(true).
spring.jpa.show-sql=false

#Desactivar TOONCAT servidor de aplicaciones web.
spring.main.web-application-type=none
